name: note-todo-app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Run JavaScript Linters and Tests
        run: npm run lint

      - name: SonarQube Analysis
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}  # Add your SonarQube token secret
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner -Dsonar.host.url=https://localhost:9000/ -Dsonar.login=${SONARQUBE_TOKEN}

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin  
          docker build -t node-todo-app .
          docker tag node-todo-app:latest javeriakashan/node-todo-app:latest
          docker push javeriakashan/node-todo-app:latest


    


    
